[platformio]
default_envs = uno ; adafruit_qtpy_esp32s2 // uno ; 

[env]
framework = arduino
monitor_speed = 9600            ; 115200, 9600

[env:uno]
platform = atmelavr
board = uno
;build_src_filter = -<*> +<01_Basic_Boucle-For.cpp>
;build_src_filter = -<*> +<02_Millis.cpp>
;build_src_filter = -<*> +<03_Millis+PortD.cpp>
build_src_filter = -<*> +<04_PortD+TIMER.cpp>

[env:adafruit_qtpy_esp32s2]
platform = espressif32
board = adafruit_qtpy_esp32s2
; board_build.f_cpu = 80000000L   ; 240, 160, 80, 40, 20 ou 10
build_src_filter = -<*> +<05_FreeRTOS.cpp>
lib_deps = adafruit/Adafruit NeoPixel @ ^1.12.3